sensor_id: # specify

sensor.source_code.main:
  class: github
  branch: main
  path: https://github.com/GauthamAnil/trel_contrib.git
sensor.main_executable: _code/sensors/bigquery_table/sensor_bigquery_table.py

manager_name: main
credentials.requested_name: default

dataset_class: # specify 
instance_ts_precision: D # change based on frequency of drop
label: master
repository: # specify destination repository

# The portion of the table name after the prefix will be parsed
# using this format into a timestamp
# instance_ts_format: # default "%Y%m%d" 

sleep_duration: 10 # The sensor sleeps for this long between checks.

bq_project: # specify
bq_dataset: # specify
bq_table_prefix: # specify

# Don't look for or insert the table into the catalog if
# it's date or time is more than this many seconds.
max_instance_age_seconds: 864000 

debug: [ ] # to debug the sensor add strings "writes" and "reads" into this list

